PRAGMA foreign_keys = ON;

DELETE FROM repo_status;
DELETE FROM case_studies;
DELETE FROM skills;
DELETE FROM projects;

INSERT INTO projects (
  id, slug, title, description, long_description, problem_solved, role, type, status,
  featured, year, demo_url, repo_url, repo_visibility, category, stack, features, screenshots
) VALUES
(
  'project_fleet_flow_ledger',
  'fleet-flow-ledger',
  'Fleet Flow Ledger',
  'Private fleet management system for vehicles, drivers, income, expenses, payments, mileage, document renewals, and exportable reports.',
  'Fleet Flow Ledger digitizes the administrative operation of a vehicle fleet. It centralizes vehicles, drivers, documents, mileage, income by unit, categorized expenses, driver payments, and financial reports in one authenticated application with Supabase persistence.',
  'Replaces scattered spreadsheet controls with a traceable workflow where each vehicle has operational history, document obligations, money movements, and reports by date or unit.',
  'Full Stack Developer',
  'Private operations and finance web system',
  'production',
  1,
  2025,
  NULL,
  NULL,
  'private',
  'business',
  '["React","TypeScript","Vite","Tailwind CSS","Supabase","PostgreSQL","Recharts","Zod"]',
  '["Private authentication","Financial dashboard","Vehicle management","Driver management","Income and expense tracking","PDF and Excel exports"]',
  '["/projects/fleet-flow-ledger/WhatsApp Image 2026-04-24 at 17.34.14.jpeg"]'
),
(
  'project_camacho_finca_raiz',
  'camacho-finca-raiz',
  'Camacho Finca Raiz',
  'Production real estate platform with property catalog, filters, detail pages, SEO routes, editable content, and WhatsApp lead funnels.',
  'Commercial platform for publishing properties and real estate projects in Cundinamarca and Tolima. It combines conversion-focused public pages with property details, filters, contact assistants, testimonials, and SEO pages generated for organic acquisition.',
  'Turns a scattered real estate inventory into an organized, indexable, easy-to-update digital channel.',
  'Frontend Software Engineer',
  'Real estate web platform',
  'production',
  1,
  2025,
  'https://camachofincaraiz.com.co',
  NULL,
  'unpublished',
  'real-estate',
  '["React","TypeScript","Vite","Tailwind CSS","Firebase","Technical SEO","Prerender"]',
  '["Property catalog","Detail pages","SEO routes","Private admin panel","WhatsApp lead flow","Responsive design"]',
  '["/projects/camacho-finca-raiz/WhatsApp Image 2026-04-24 at 17.08.14.jpeg"]'
),
(
  'project_agenda_inmobiliaria',
  'agenda-inmobiliaria-familiar',
  'Agenda Inmobiliaria Familiar',
  'Private real estate agenda PWA with clients, properties, appointments, roles, RLS, push notifications, persistent queue, and Supabase Edge Functions.',
  'Agenda Inmobiliaria Familiar centralizes commercial follow-up for a family real estate operation. It supports login, client registration, property management, appointment creation, agenda views, outcome documentation, and push alerts through serverless functions.',
  'Organizes a process that usually lives across calls, messages, and loose notes into a traceable appointment workflow.',
  'Full Stack Developer',
  'Private real estate management PWA',
  'published',
  1,
  2026,
  NULL,
  'https://github.com/Andresito202/agenda-inmobiliaria-familiar',
  'public',
  'business',
  '["React","TypeScript","Vite","Tailwind CSS","Supabase","PostgreSQL","RLS","PWA","Web Push"]',
  '["Client management","Property management","Appointment calendar","Internal roles","Push notifications","Edge Functions"]',
  '["/projects/agenda-inmobiliaria-familiar/WhatsApp Image 2026-04-30 at 16.08.32.jpeg"]'
),
(
  'project_english_tutor',
  'andres-english-tutor',
  'Andres English Tutor',
  'AI English tutor for speaking practice with Gemini, microphone input, voice playback, levels, lessons, quizzes, local progress, and serverless AI usage control.',
  'Educational SPA built with React and Vite for spoken English practice. It combines a Gemini-powered conversational tutor, microphone input, speech synthesis, guided lessons, quizzes, and Supabase Edge Functions to protect the API key.',
  'Reduces friction for spoken English practice from the browser while keeping the AI key outside the public frontend.',
  'Frontend AI Developer',
  'AI English tutor with voice and Edge Functions',
  'published',
  1,
  2026,
  'https://andresito202.github.io/andres-english-tutor/',
  'https://github.com/Andresito202/andres-english-tutor',
  'public',
  'business',
  '["React","Vite","JavaScript","Google Gemini API","Supabase Edge Functions","Web Speech API","GitHub Actions"]',
  '["AI tutor chat","Speech recognition","Voice playback","Guided learning path","Quizzes","GitHub Pages deploy"]',
  '["/projects/andres-english-tutor/WhatsApp Image 2026-05-04 at 18.34.27 (1).jpeg"]'
),
(
  'project_supermercado_avicola',
  'supermercado-avicola',
  'Supermercado Avicola',
  'Full-stack poultry operations system with FastAPI API, JWT, roles, purchases, batches, FIFO inventory, POS, cash desk, reports, auditing, and Docker.',
  'Administrative platform covering the full operating cycle of a poultry products business. The API separates authentication, catalog, suppliers, purchases, batches, inventory, sales, cash desk, shrinkage, reporting, and auditing domains.',
  'Prevents sales, purchases, inventory, and cash desk from being handled as isolated processes.',
  'Full Stack Developer',
  'Administrative system and commercial operations',
  'in_development',
  0,
  2025,
  NULL,
  'https://github.com/Andresito202/supermercado-avicola',
  'public',
  'business',
  '["Python","FastAPI","SQLAlchemy","Alembic","PostgreSQL","Pydantic","JWT","Docker","Pytest"]',
  '["JWT auth","Role control","Purchases","FIFO inventory","Cash desk","Operational reports","Auditing"]',
  '["/projects/supermercado-avicola/WhatsApp Image 2026-04-24 at 17.23.28.jpeg"]'
),
(
  'project_diegus_fashion',
  'diegus-fashion',
  'Diegus Fashion',
  'Editable commercial jacket catalog with responsive storefront, real-time Firestore, private admin panel, product and category CRUD, and WhatsApp orders.',
  'Catalog-style store for wholesale and retail jacket sales. The public view renders categories, products, images, sizes, colors, prices, and payment methods while the admin panel manages catalog data from Firebase.',
  'Gives the business an updatable digital storefront without depending on a developer for each price, image, or category change.',
  'Frontend Developer',
  'Catalog-style online store with admin panel',
  'published',
  0,
  2026,
  'https://andresito202.github.io/DiegusFashion/',
  'https://github.com/Andresito202/DiegusFashion',
  'public',
  'real-estate',
  '["HTML5","CSS3","JavaScript","Bootstrap 5","Firebase Auth","Firestore","WhatsApp API"]',
  '["Responsive catalog","Firestore data","Private admin panel","Product CRUD","WhatsApp orders","GitHub Pages"]',
  '["/projects/diegus-fashion/WhatsApp Image 2026-04-24 at 19.58.40.jpeg"]'
),
(
  'project_batalla_naval',
  'batalla-naval-3d',
  'Batalla Naval 3D',
  'Full-stack Battleship game with React 3D client, shared TypeScript logic, AI, LAN rooms, Socket.IO, PWA, tests, and Docker deployment.',
  'Batalla Naval 3D combines a visual browser experience with separate client, server, and shared-domain architecture. The client uses React, Three.js, and local state while the server coordinates rooms and synchronization.',
  'Brings a classic game into a maintainable web implementation with shared tested rules between frontend and backend.',
  'Full Stack Game Developer',
  'Full-stack web game and 3D PWA',
  'published',
  0,
  2025,
  'https://batalla-naval-3d.onrender.com',
  NULL,
  'unpublished',
  'games',
  '["React","TypeScript","Vite","Three.js","React Three Fiber","Zustand","Express","Socket.IO","Vitest","Docker"]',
  '["3D board","Shared game rules","AI","Multiplayer rooms","PWA","Automated tests"]',
  '["/projects/batalla-naval-3d/1.jpeg"]'
),
(
  'project_triki',
  'triki',
  'Triki',
  'Web tic-tac-toe with local mode, AI, room-based multiplayer using Express and Socket.IO, real-time sync, persistent room score, and PWA support.',
  'Casual tic-tac-toe game with a static client and Node server. The server creates private rooms, validates turns, syncs moves through Socket.IO, keeps scores, and cleans up matches.',
  'Turns a simple game into a fast online experience without authentication or installation.',
  'Full Stack JavaScript Developer',
  'Interactive web game',
  'published',
  0,
  2025,
  'https://andresito202.github.io/triki/',
  'https://github.com/Andresito202/triki',
  'public',
  'games',
  '["Node.js","Express","Socket.IO","HTML5","CSS3","JavaScript","PWA","GitHub Pages"]',
  '["Local mode","AI mode","Online rooms","Socket.IO sync","Scoreboard","PWA"]',
  '["/projects/triki/WhatsApp Image 2026-04-24 at 22.43.01.jpeg"]'
);

INSERT INTO repo_status (id, project_slug, repo_url, visibility, is_available) VALUES
  ('repo_fleet_flow_ledger', 'fleet-flow-ledger', NULL, 'private', 0),
  ('repo_camacho_finca_raiz', 'camacho-finca-raiz', NULL, 'unpublished', 0),
  ('repo_agenda_inmobiliaria', 'agenda-inmobiliaria-familiar', 'https://github.com/Andresito202/agenda-inmobiliaria-familiar', 'public', 1),
  ('repo_english_tutor', 'andres-english-tutor', 'https://github.com/Andresito202/andres-english-tutor', 'public', 1),
  ('repo_supermercado_avicola', 'supermercado-avicola', 'https://github.com/Andresito202/supermercado-avicola', 'public', 1),
  ('repo_diegus_fashion', 'diegus-fashion', 'https://github.com/Andresito202/DiegusFashion', 'public', 1),
  ('repo_batalla_naval', 'batalla-naval-3d', NULL, 'unpublished', 0),
  ('repo_triki', 'triki', 'https://github.com/Andresito202/triki', 'public', 1);

INSERT INTO skills (id, name, category, level, icon, display_order) VALUES
  ('skill_react', 'React', 'frontend', 5, 'react', 10),
  ('skill_typescript', 'TypeScript', 'language', 5, 'typescript', 20),
  ('skill_node', 'Node.js', 'backend', 4, 'node', 30),
  ('skill_fastapi', 'FastAPI', 'backend', 4, 'python', 40),
  ('skill_supabase', 'Supabase', 'backend', 4, 'database', 50),
  ('skill_postgres', 'PostgreSQL', 'database', 4, 'database', 60),
  ('skill_cloudflare', 'Cloudflare Workers', 'backend', 4, 'cloud', 70),
  ('skill_seo', 'Technical SEO', 'growth', 4, 'search', 80);

INSERT INTO case_studies (id, project_id, slug, problem, solution, architecture, results, lessons) VALUES
(
  'case_fleet_flow_ledger',
  'project_fleet_flow_ledger',
  'fleet-flow-ledger-private-operations-system',
  'The client managed fleet income, vehicle expenses, driver payments, and document renewals through scattered manual controls.',
  'I built a private authenticated system with structured modules for vehicles, drivers, income, expenses, payments, reports, and exports.',
  'React and TypeScript frontend, Supabase Auth, PostgreSQL persistence, typed forms, dashboard KPIs, and export utilities.',
  'The project became a portfolio-grade example of real client operations software while protecting private business data.',
  'Private projects can be presented professionally through anonymized screenshots, architecture, and outcomes without exposing source code.'
),
(
  'case_portfolio_api',
  'project_agenda_inmobiliaria',
  'portfolio-api-content-source',
  'The portfolio needed a reliable source of truth for projects, repo visibility, and contact messages without hardcoding every future update.',
  'This API separates public portfolio data from private admin operations and exposes stable versioned endpoints.',
  'Cloudflare Workers, Hono, D1, Drizzle, Zod validation, OpenAPI documentation, CORS restrictions, API-key admin routes, and CI checks.',
  'The portfolio can evolve from a static site into a full-stack professional system with a free serverless backend.',
  'A strong portfolio project should demonstrate architecture, validation, deployment, documentation, and security decisions.'
);
